name: lotto_app
description: Lotto App - Digital Lottery Application
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP requests
  http: ^1.1.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # JWT token decoder
  jwt_decoder: ^2.0.1
  
  # State management
  provider: ^6.1.1
  
  # Offline storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Connectivity
  connectivity_plus: ^5.0.2
  
  # UI components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets configuration
  assets:
    - assets/config/
    - assets/images/
  
  # Fonts (optional - add if you have custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
